import { Schema } from "../schema";

export const sblSimple: Schema = {
  ALEF: "",
  BET: "v",
  BET_DAGESH: "b",
  GIMEL: "g",
  DALET: "d",
  HE: "h",
  VAV: "v",
  ZAYIN: "z",
  HET: "kh",
  TET: "t",
  YOD: "y",
  KAF: "kh",
  KAF_DAGESH: "k",
  FINAL_KAF: "kh",
  LAMED: "l",
  MEM: "m",
  FINAL_MEM: "m",
  NUN: "n",
  FINAL_NUN: "n",
  SAMEKH: "s",
  AYIN: "",
  PE: "f",
  PE_DAGESH: "p",
  FINAL_PE: "f",
  TSADI: "ts",
  FINAL_TSADI: "ts",
  QOF: "q",
  RESH: "r",
  SIN: "s",
  SHIN: "sh",
  TAV: "t",
  DAGESH: "",
  DAGESH_CHAZAQ: true,
  VOCAL_SHEVA: "e",
  PATAH: "a",
  HATAF_PATAH: "a",
  QAMATS: "a",
  HATAF_QAMATS: "o",
  SEGOL: "e",
  HATAF_SEGOL: "e",
  TSERE: "e",
  HIRIQ: "i",
  HOLAM: "o",
  HOLAM_HASER: "o",
  QUBUTS: "u",
  QAMATS_HE: "ah",
  SEGOL_HE: "eh",
  TSERE_HE: "eh",
  SEGOL_YOD: "e",
  HIRIQ_YOD: "i",
  TSERE_YOD: "e",
  FURTIVE_PATAH: "a",
  QAMATS_QATAN: "o",
  HOLAM_VAV: "o",
  SHUREQ: "u",
  MS_SUFX: "ayw",
  PASEQ: "",
  SOF_PASUQ: "",
  MAQAF: "-",
  DIVINE_NAME: "yhwh",
  ADDITIONAL_FEATURES: [
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E9}\u{05C1}\u{05BC}",
      TRANSLITERATION: "sh"
    },
    {
      FEATURE: "cluster",
      HEBREW: "\u{05E6}\u{05BC}",
      TRANSLITERATION: "ts"
    }
  ],
  longVowels: true,
  sqnmlvy: true,
  qametsQatan: true,
  wawShureq: true,
  article: true,
  allowNoNiqqud: true,
  strict: false,
  holemHaser: "remove"
};
