import { Schema } from "./interfaces";

const sbl: Schema = {
  VOCAL_SHEVA: "ǝ",
  HATAF_SEGOL: "ĕ",
  HATAF_PATAH: "ă",
  HATAF_QAMATS: "ŏ",
  HIRIQ: "i",
  TSERE: "ē",
  SEGOL: "e",
  PATAH: "a",
  QAMATS: "ā",
  HOLAM: "ō",
  QUBUTS: "ū",
  DAGESH_CHAZAQ: true,
  MAQAF: "-",
  QAMATS_QATAN: "o",
  FURTIVE_PATAH: "a",
  HIRIQ_YOD: "î",
  TSERE_YOD: "ê",
  SEGOL_YOD: "ê",
  SHUREQ: "û",
  HOLAM_VAV: "ô",
  QAMATS_HE: "â",
  MS_SUFX: "āyw",
  ALEF: "ʾ",
  BET: "b",
  GIMEL: "g",
  DALET: "d",
  HE: "h",
  VAV: "w",
  ZAYIN: "z",
  HET: "ḥ",
  TET: "ṭ",
  YOD: "y",
  FINAL_KAF: "k",
  KAF: "k",
  LAMED: "l",
  FINAL_MEM: "m",
  MEM: "m",
  FINAL_NUN: "n",
  NUN: "n",
  SAMEKH: "s",
  AYIN: "ʿ",
  FINAL_PE: "p",
  PE: "p",
  FINAL_TSADI: "ṣ",
  TSADI: "ṣ",
  QOF: "q",
  RESH: "r",
  SHIN: "š",
  SIN: "ś",
  TAV: "t",
  DIVINE_NAME: "yhwh"
};

export { sbl };
